name: Apply formatting

on:
    - push
    - pull_request

jobs:
    format:
        name: Apply formatting
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  # Needed in order to work on `pull_request` event
                  # See https://github.com/stefanzweifel/git-auto-commit-action#example-workflow
                  ref: ${{ github.head_ref }}

            ## PYTHON ##############################################################################

            - name: Install `uv`
              uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0
              with:
                  version: "0.5.6"

            - name: Set up Python
              uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
              with:
                  python-version: "3.12"

            - name: Install requirements
              run: uv sync --all-extras --frozen

            - name: Format Python code
              run: uv run --frozen ruff format

            ## OTHER ###############################################################################
            
            - name: Set up Node
              uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
              with:
                node-version: '22.12.0'
                cache: 'npm'
                cache-dependency-path: '**/.github/workflows/*.yml'

            - name: Run Prettier
              run: |
                npm install --no-save prettier prettier-plugin-toml
                npx prettier . --write

            ## COMMIT CHANGES ######################################################################

            - name: Commit formatting
              uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
              with:
                  commit_message: "style: Apply standardised formatting"
