on:
  release:
    types:
      - published
  workflow_dispatch:
    

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/tattl
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install `uv`
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.6"
      
      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev --no-editable

      - name: Run checks and tests
        run: |
          uv run ruff check
          uv run mypy
          uv run pytest
          uv run ruff format
      
      - name: Build
        run: uv build

      - name: Publish to PyPI
        run: uv publish
        